import { describe, expect, it } from "vitest"
import { WEEK_DAYS } from "@/features/core/models"
import { buildHourlyProfile, copyCoverageProfile, createEmptySector, createSectorRepository, validateSectorDemand } from "@/features/sectors"
import type { StoreConfig } from "@/features/store/schemas/store.schema"

const store = { openingHours: WEEK_DAYS.map((day) => ({ day, closed: day === "sunday", opensAt: "08:00", closesAt: "20:00" })), minShiftDuration: 120 } as StoreConfig
function complete() { const base = createEmptySector("sector_1"); return { ...base, name: "Accueil", hours: base.hours.map((day) => day.day === "monday" || day.day === "tuesday" ? { ...day, closed: false } : day), coverage: { standardDay: "monday" as const, profiles: { monday: buildHourlyProfile("09:00", "18:00", 2), tuesday: buildHourlyProfile("09:00", "18:00", 2) } }, weeklyDistribution: { monday: 50, tuesday: 50, wednesday: 0, thursday: 0, friday: 0, saturday: 0, sunday: 0 }, competencies: [{ id: "skill_1", name: "Conseil", archived: false, order: 0 }] } }

describe("configuration de demande secteur", () => {
  it("valide et persiste une configuration complète avec règles et compétences liées", () => { const sector = complete(); expect(validateSectorDemand(sector, store)).toEqual([]); let value: string | null = null; const repository = createSectorRepository({ getItem: () => value, setItem: (_key, next) => { value = next } }); repository.save([sector]); expect(repository.list()[0].shiftRules.minimumShiftDuration).toBeNull(); expect(repository.list()[0].competencies[0].name).toBe("Conseil") })
  it("copie un profil sans lier les exceptions éditées", () => { const copied = copyCoverageProfile(complete(), "monday", "tuesday"); const changed = { ...copied, coverage: { ...copied.coverage, profiles: { ...copied.coverage.profiles, tuesday: copied.coverage.profiles.tuesday!.map((slot, index) => index === 0 ? { ...slot, employees: 7 } : slot) } } }; expect(changed.coverage.profiles.monday![0].employees).toBe(2); expect(changed.coverage.profiles.tuesday![0].employees).toBe(7) })
  it("exige la couverture complète et exactement 100 %", () => { const sector = complete(); const broken = { ...sector, coverage: { ...sector.coverage, profiles: { ...sector.coverage.profiles, monday: sector.coverage.profiles.monday!.slice(1) } }, weeklyDistribution: { ...sector.weeklyDistribution, monday: 49 } }; const issues = validateSectorDemand(broken, store); expect(issues.some((issue) => issue.path === "coverage.monday")).toBe(true); expect(issues.some((issue) => issue.path === "weeklyDistribution")).toBe(true) })
  it("autorise 0 % sur les jours fermés", () => { expect(validateSectorDemand(complete(), store).some((issue) => issue.path === "weeklyDistribution")).toBe(false) })
  it("rejette les horaires invalides ou hors magasin", () => { const sector = complete(); const invalid = { ...sector, hours: sector.hours.map((day) => day.day === "monday" ? { ...day, opensAt: "07:00" } : day) }; expect(validateSectorDemand(invalid, store).some((issue) => issue.path === "hours.monday")).toBe(true) })
  it("valide et persiste la coupure maximale du secteur", () => { const valid = { ...complete(), shiftRules: { ...complete().shiftRules, splitShiftAllowed: true, maximumSplitDuration: 90 } }; expect(validateSectorDemand(valid, store)).toEqual([]); let value: string | null = null; const repository = createSectorRepository({ getItem: () => value, setItem: (_key, next) => { value = next } }); repository.save([valid]); expect(repository.list()[0].shiftRules.maximumSplitDuration).toBe(90); const invalid = { ...valid, shiftRules: { ...valid.shiftRules, maximumSplitDuration: 100 } }; expect(validateSectorDemand(invalid, store).some((issue) => issue.path === "shiftRules.maximumSplitDuration")).toBe(true) })
})
