import { describe, expect, it } from "vitest"
import { contractualMinutes, WEEK_DAYS, type EmployeeId } from "@/features/core/models"
import type { PlanningGenerationInput } from "@/features/core/planning-generator"
import { planningGenerator as sprintAwarePlanningGenerator } from "@/features/core/planning-generator"
import { brand, builtInRegistry, contract, demand, employee, requirement, settings, store } from "@/features/core/planning-generator/__tests__/fixtures"

const planningGenerator = { generate: (input: PlanningGenerationInput) => sprintAwarePlanningGenerator.generate({ ...input, business: { ...input.business, pipelineMode: "legacy-v2" } }) }

const MON = "2026-07-06", TUE = "2026-07-07"
function scenario(): PlanningGenerationInput {
  const closingEmployee = { ...employee("closer"), capabilities: ["CAN_CLOSE"] }
  const openingEmployee = { ...employee("opener"), capabilities: ["CAN_OPEN"] }
  const closing = { ...requirement("closing", MON, 1), window: { date: MON, start: "19:00", end: "23:00" } }
  const opening = { ...requirement("opening", TUE, 1), window: { date: TUE, start: "08:00", end: "12:00" } }
  const configuredStore = { ...store(), openingHours: store().openingHours.map((day) => ({ ...day, opensAt: "08:00", closesAt: "23:00" })) }
  return { store: configuredStore, employees: [closingEmployee, openingEmployee], contracts: [{ ...contract("closer", ["monday", "tuesday"]), weeklyHours: 8 }, { ...contract("opener", ["monday", "tuesday"]), weeklyHours: 8 }], demand: demand([opening, closing]), registry: builtInRegistry(), settings: { ...settings(), minimumRestMinutes: 660, maximumDailyMinutes: 600, timeIncrementMinutes: 15 }, employeeConstraints: [{ id: brand("max_closer"), employeeId: brand<EmployeeId>("closer"), type: "MAX_CLOSINGS", value: 1 }], business: { employeePreferences: [{ employeeId: brand<EmployeeId>("closer"), prefersClosing: true }, { employeeId: brand<EmployeeId>("opener"), prefersClosing: false }] } }
}
function realisticScenario(windows: readonly [string, string][], options: { splitAllowed?: boolean; maximumSplitDuration?: number; employeeSplitAllowed?: boolean; weeklyHours?: number } = {}): PlanningGenerationInput {
  const requirements = windows.map(([start, end], index) => ({ ...requirement(`hour_${index}`, MON, 1), window: { date: MON, start, end } }))
  const worker = { ...employee("worker"), capabilities: ["CAN_OPEN", "CAN_CLOSE", ...(options.employeeSplitAllowed ? ["CAN_SPLIT_SHIFT"] : [])] }
  const configuredStore = { ...store(), openingHours: store().openingHours.map((day) => ({ ...day, opensAt: "08:00", closesAt: "18:00" })) }
  return { store: configuredStore, employees: [worker], contracts: [{ ...contract("worker", ["monday"]), weeklyHours: options.weeklyHours ?? 10 }], demand: demand(requirements), registry: builtInRegistry(), settings: { ...settings(), maximumDailyMinutes: 600, timeIncrementMinutes: 15 }, business: { sectors: [{ id: "sector_1", name: "Secteur test", active: true, weeklyDistribution: Object.fromEntries(WEEK_DAYS.map((day) => [day, day === "monday" ? 100 : 0])) as Record<(typeof WEEK_DAYS)[number], number>, minimumShiftDuration: 120, splitShiftAllowed: options.splitAllowed ?? false, maximumSplitDuration: options.maximumSplitDuration ?? 90, assignedEmployeeIds: [worker.id], requirementIds: requirements.map((item) => String(item.id)) }] } }
}
const minutesFor = (result: ReturnType<typeof planningGenerator.generate>, employeeId: string) => result.assignments.filter((assignment) => assignment.employeeId === brand<EmployeeId>(employeeId)).reduce((sum, assignment) => { const shift = result.shifts.find((item) => item.id === assignment.shiftId)!; const [sh, sm] = shift.segments[0].startTime.split(":").map(Number), [eh, em] = shift.segments[0].endTime.split(":").map(Number); return sum + eh * 60 + em - sh * 60 - sm }, 0)
const shiftMinutes = (start: string, end: string) => { const [sh, sm] = start.split(":").map(Number), [eh, em] = end.split(":").map(Number); return eh * 60 + em - sh * 60 - sm }

describe("business planning pipeline V2", () => {
  it("exécute les phases dans l’ordre et affecte fermeture puis ouverture", () => { const result = planningGenerator.generate(scenario()); expect(result.phaseTrace).toEqual(["validation", "demand-calculation", "weekly-allocation", "daily-placement", "closing-assignment", "legal-rest", "opening-assignment", "coverage", "contract-completion", "global-weekly-repair", "optimisation", "final-validation"]); expect(String(result.assignments[0].shiftId)).toContain("closer_2026-07-06_closing"); expect(result.assignments.find((item) => String(item.shiftId).endsWith("_opening"))?.employeeId).toBe(brand<EmployeeId>("opener")) })
  it("bloque une ouverture incompatible avec le repos légal", () => { const input = scenario(); const onlyCloser = { ...input.employees[0], capabilities: ["CAN_CLOSE", "CAN_OPEN"] }; const result = planningGenerator.generate({ ...input, employees: [onlyCloser], contracts: [{ ...contract("closer", ["monday", "tuesday"]), weeklyHours: 8 }] }); expect(result.assignments.some((item) => String(item.shiftId).endsWith("_opening") && item.employeeId === onlyCloser.id)).toBe(false); expect(result.issues.some((item) => item.code === "minimum_rest")).toBe(false) })
  it("construit la couverture et complète exactement les contrats en étendant avant de créer", () => { const result = planningGenerator.generate(scenario()); expect(result.coverage.statistics.covered).toBe(2); expect(minutesFor(result, "closer")).toBe(480); expect(minutesFor(result, "opener")).toBe(480); expect(result.explanations.some((item) => item.phase === "contract-completion" && item.reasons.some((reason) => reason.includes("étendu")))).toBe(true) })
  it("signale explicitement un planning dégradé", () => { const input = scenario(), closing = input.demand.requirements.find((item) => item.id === brand("closing"))!; const result = planningGenerator.generate({ ...input, employees: [input.employees[0]], contracts: [{ ...contract("closer"), weeklyHours: 4 }], demand: demand([{ ...closing, minEmployees: 2 }]) }); expect(result.status).toBe("degraded"); expect(result.issues.some((item) => item.code === "coverage_degraded")).toBe(true) })
  it("reste déterministe à entrées identiques", () => { const project = (result: ReturnType<typeof planningGenerator.generate>) => ({ shifts: result.shifts, assignments: result.assignments, explanations: result.explanations, issues: result.issues, trace: result.phaseTrace }); expect(project(planningGenerator.generate(scenario()))).toEqual(project(planningGenerator.generate(scenario()))) })
  it("transforme dix besoins horaires en une seule journée continue sans micro-shifts", () => { const windows = Array.from({ length: 10 }, (_, index) => [`${String(8 + index).padStart(2, "0")}:00`, `${String(9 + index).padStart(2, "0")}:00`] as [string, string]); const result = planningGenerator.generate(realisticScenario(windows)); expect(result.assignments).toHaveLength(1); expect(result.shifts).toHaveLength(1); expect(result.shifts[0].segments).toEqual([{ startTime: "08:00", endTime: "18:00" }]); expect(result.coverage.statistics.covered).toBe(10); expect(minutesFor(result, "worker")).toBe(600) })
  it("fusionne les fragments adjacents ou séparés de quinze minutes", () => { const result = planningGenerator.generate(realisticScenario([["09:00", "12:00"], ["12:15", "17:00"]], { weeklyHours: 8 })); expect(result.assignments).toHaveLength(1); expect(result.shifts[0].segments[0]).toEqual({ startTime: "09:00", endTime: "17:00" }); expect(result.coverage.statistics.covered).toBe(2) })
  it("interdit une deuxième plage quand la coupure n’est pas autorisée", () => { const result = planningGenerator.generate(realisticScenario([["08:00", "11:00"], ["15:00", "18:00"]], { weeklyHours: 3 })); expect(result.assignments).toHaveLength(1); expect(result.issues.some((item) => item.code === "coverage_degraded")).toBe(true) })
  it("autorise au maximum deux shifts si salarié et secteur l’autorisent", () => { const result = planningGenerator.generate(realisticScenario([["08:00", "11:00"], ["12:00", "15:00"]], { splitAllowed: true, employeeSplitAllowed: true, maximumSplitDuration: 90, weeklyHours: 6 })); expect(result.assignments).toHaveLength(2); expect(result.shifts).toHaveLength(2); expect(result.issues.some((item) => item.code.startsWith("split_") || item.code === "too_many_daily_shifts")).toBe(false) })
  it("refuse une coupure qui dépasse la durée maximale du secteur", () => { const result = planningGenerator.generate(realisticScenario([["08:00", "11:00"], ["13:00", "16:00"]], { splitAllowed: true, employeeSplitAllowed: true, maximumSplitDuration: 90, weeklyHours: 3 })); expect(result.assignments).toHaveLength(1); expect(result.coverage.statistics.underCovered).toBe(1) })
  it("bloque un contrat impossible à compléter sans micro-shift", () => { const input = realisticScenario([["09:00", "10:00"]], { weeklyHours: 1 }); const result = planningGenerator.generate(input); expect(result.status).toBe("blocked"); expect(result.issues).toContainEqual(expect.objectContaining({ code: "contract_inexact", severity: "blocking", details: expect.objectContaining({ contractualTargetMinutes: 60, assignableMinutes: 0, differenceMinutes: 60 }) })); expect(result.assignments).toHaveLength(0) })
  it("représente 36 h 45 par exactement 2 205 minutes", () => { expect(contractualMinutes({ weeklyMinutes: 2_205, weeklyHours: 36.75 })).toBe(2_205); expect(contractualMinutes({ weeklyHours: 36.75 })).toBe(2_205) })
  it("répare globalement un reste contractuel impossible par extension locale", () => { const input = realisticScenario([["17:00", "18:00"]], { weeklyHours: 4.25 }); const sector = input.business!.sectors![0]; const result = planningGenerator.generate({ ...input, contracts: input.contracts!.map((item) => ({ ...item, weeklyMinutes: 255 })), business: { ...input.business, sectors: [{ ...sector, minimumShiftDuration: 240 }] } }); expect(result.status).toBe("complete"); expect(minutesFor(result, "worker")).toBe(255); expect(result.shifts[0].segments[0]).toEqual({ startTime: "13:45", endTime: "18:00" }); expect(result.repairAttempts.some((attempt) => attempt.family === "coordinated-portions" && attempt.generated > 0 && attempt.evaluated > 0)).toBe(true) })
  it("garde indépendants deux shifts issus du même besoin (255 et 240 minutes)", () => { const base = realisticScenario([["17:00", "18:00"]]); const a = { ...employee("a"), capabilities: ["CAN_CLOSE"] }, b = { ...employee("b"), capabilities: ["CAN_CLOSE"] }; const requirementItem = { ...base.demand.requirements[0], minEmployees: 2 }; const sector = base.business!.sectors![0]; const result = planningGenerator.generate({ ...base, employees: [a, b], contracts: [{ ...contract("a", ["monday"]), weeklyMinutes: 255, weeklyHours: 4.25 }, { ...contract("b", ["monday"]), weeklyMinutes: 240, weeklyHours: 4 }], demand: demand([requirementItem]), business: { ...base.business, sectors: [{ ...sector, minimumShiftDuration: 240, assignedEmployeeIds: [a.id, b.id] }] } }); const shiftA = result.shifts.find((shift) => result.assignments.some((assignment) => assignment.employeeId === a.id && assignment.shiftId === shift.id))!, shiftB = result.shifts.find((shift) => result.assignments.some((assignment) => assignment.employeeId === b.id && assignment.shiftId === shift.id))!; expect(result.status).toBe("complete"); expect(shiftA.id).not.toBe(shiftB.id); expect(shiftA).not.toBe(shiftB); expect(shiftA.segments[0]).toEqual({ startTime: "13:45", endTime: "18:00" }); expect(shiftB.segments[0]).toEqual({ startTime: "14:00", endTime: "18:00" }); expect(minutesFor(result, "a")).toBe(255); expect(minutesFor(result, "b")).toBe(240) })
  it("ne bloque qu’après avoir épuisé la recherche réellement générée", () => { const result = planningGenerator.generate(realisticScenario([["09:00", "10:00"]], { weeklyHours: 1 })); const repair = result.explanations.findLast((item) => item.phase === "global-weekly-repair"); expect(result.status).toBe("blocked"); expect(repair?.message).toContain("épuisement de la recherche bornée"); expect(repair?.reasons.some((reason) => reason.includes("Opération tentée"))).toBe(false); expect(result.repairAttempts.every((attempt) => attempt.generated > 0)).toBe(true) })
  it("construit une fermeture cohérente respectant un minimum de quatre heures", () => { const input = realisticScenario([["17:00", "18:00"]], { weeklyHours: 4 }); const sector = input.business!.sectors![0]; const result = planningGenerator.generate({ ...input, business: { ...input.business, sectors: [{ ...sector, minimumShiftDuration: 240 }] } }); expect(result.status).toBe("complete"); expect(result.shifts[0].segments[0]).toEqual({ startTime: "14:00", endTime: "18:00" }); expect(result.shifts.every((shift) => shiftMinutes(shift.segments[0].startTime, shift.segments[0].endTime) >= 240)).toBe(true) })
  it("garantit les contrats exacts pour les plannings complets et dégradés", () => { const covered = planningGenerator.generate(scenario()); expect(["complete", "degraded"]).toContain(covered.status); expect(minutesFor(covered, "closer")).toBe(480); expect(minutesFor(covered, "opener")).toBe(480); const degraded = planningGenerator.generate(realisticScenario([["08:00", "11:00"], ["15:00", "18:00"]], { weeklyHours: 3 })); expect(degraded.status).toBe("degraded"); expect(minutesFor(degraded, "worker")).toBe(180) })
  it("affecte initialement une seule fermeture quand une seule est demandée", () => { const result = planningGenerator.generate(scenario()); const closing = result.coverage.results.find((item) => item.requirementId === brand("closing")); expect(closing?.assignedCount).toBe(1) })
  it("accepte un surplus de couverture justifié par les contrats exacts", () => { const base = realisticScenario([["08:00", "12:00"], ["12:00", "16:00"]], { weeklyHours: 8 }); const second = { ...employee("worker_2"), capabilities: ["CAN_OPEN", "CAN_CLOSE"] }; const sector = base.business!.sectors![0]; const result = planningGenerator.generate({ ...base, employees: [...base.employees, second], contracts: [...base.contracts!, { ...contract("worker_2", ["monday"]), weeklyHours: 8 }], business: { ...base.business, sectors: [{ ...sector, assignedEmployeeIds: [...sector.assignedEmployeeIds, second.id] }] } }); expect(result.status).toBe("degraded"); expect(minutesFor(result, "worker")).toBe(480); expect(minutesFor(result, "worker_2")).toBe(480); expect(result.issues.some((item) => item.code === "coverage_surplus_summary")).toBe(true) })
  it("agrège les surplus dans un seul message principal par jour", () => { const base = realisticScenario([["08:00", "10:00"], ["10:00", "12:00"], ["12:00", "14:00"]], { weeklyHours: 6 }); const second = { ...employee("worker_2"), capabilities: ["CAN_OPEN", "CAN_CLOSE"] }; const sector = base.business!.sectors![0]; const result = planningGenerator.generate({ ...base, employees: [...base.employees, second], contracts: [...base.contracts!, { ...contract("worker_2", ["monday"]), weeklyHours: 6 }], business: { ...base.business, sectors: [{ ...sector, assignedEmployeeIds: [...sector.assignedEmployeeIds, second.id] }] } }); expect(result.issues.filter((item) => item.code === "coverage_surplus_summary")).toHaveLength(1); expect(result.issues.some((item) => item.code === "coverage_surplus")).toBe(false) })
  it("expose la limite multi-secteur sans allocation contractuelle", () => { const input = realisticScenario([["09:00", "13:00"]], { weeklyHours: 4 }); const sector = input.business!.sectors![0]; const result = planningGenerator.generate({ ...input, business: { ...input.business, sectors: [sector, { ...sector, id: "second", name: "Second" }] } }); expect(result.status).toBe("blocked"); expect(result.issues).toContainEqual(expect.objectContaining({ code: "multi_sector_contract_allocation_missing", severity: "blocking" })) })
})
